name: 'Release Draft'
description: 'Creates & updates GitHub release draft, automatically generates release notes, and bumps semver compliant tags.'
author: 'Chris Kerins'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  commitish:
    description: 'Target of release. Default: default branch'
    required: false
  bump:
    description: 'Semver bump type. Options: major, minor, patch, premajor, preminor, prepatch, or prerelease.  Default level is patch. Only one version may be specified.'
    required: false
    default: 'patch'
  release-strategy:
    description: 'See Release Strategy section for details.'
    required: false
    default: 'single'
  publish-strategy:
    description: 'See Publish Strategy section for details.'
    required: false
    default: 'manual'
outputs:
  id:
    description: 'The ID of the Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'save'
  color: 'blue'
